name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  example_matrix:
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ 4.x }}
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          apt-get install npm node-grunt-cli 
          npm install --force
          npm install grunt-electron grunt-electron-installer-debian grunt-electron-installer-redhat

      - name: build
        run: |
          grunt --base build
