name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  example_matrix:
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-20.04]        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          npm install --force
          cd build
          npm install grunt-electron grunt-electron-installer-debian grunt-electron-installer-redhat
      - name: build
        run: |
          cd build
          grunt
      - uses: actions/upload-artifact@v3
        name: linux installers
        with:
          path: | 
            build/dist/*.deb
            build/dist/*.rpm